INSERT INTO programs VALUES('TEST_PROGRAM','TESTP');

INSERT INTO departments VALUES('TESTD','TEST_DEPARTMENT');

INSERT INTO host VALUES('TESTD','TEST_PROGRAM');

INSERT INTO courses VALUES('TESLIM', 7.5, 'TESTD');
INSERT INTO courses VALUES('TSNLIM', 7.5, 'TESTD');
INSERT INTO courses VALUES('TESRE1',7.5, 'TESTD');
INSERT INTO courses VALUES('TESRE2',7.5, 'TESTD');

INSERT INTO requires VALUES('TESRE1','TESRE2');

INSERT INTO limitedCourses VALUES('TESLIM',2);

INSERT INTO students VALUES(101,101,'Tester1','TEST_PROGRAM');
INSERT INTO students VALUES(102,102,'Tester2','TEST_PROGRAM');
INSERT INTO students VALUES(103,103,'Tester3','TEST_PROGRAM');
INSERT INTO students VALUES(104,104,'Tester4','TEST_PROGRAM');
INSERT INTO students VALUES(105,105,'Tester5','TEST_PROGRAM');
